#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

# Polkit
lxpolkit &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width 2
bspc config window_gap 8
bspc config normal_border_color "#313244"
bspc config focused_border_color "#7f849c"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
# bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config pointer_motion_interval 5

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

# Autostart
~/.config/polybar/launch.sh &
picom -b &
dunst &
xsetroot -cursor_name left_ptr &
nitrogen --restore &
emacs --daemon
